# Generated by Django 5.2.17 on 2026-08-24 23:05

import django.db.models.deletion
import django.db.models.manager
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('clinics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='excluido')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='excluido em')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='ativo')),
                ('name', models.CharField(max_length=180, verbose_name='razao social')),
                ('trade_name', models.CharField(blank=True, max_length=180, verbose_name='nome fantasia')),
                ('slug', models.SlugField(max_length=180, unique=True, verbose_name='identificador')),
                ('document', models.CharField(blank=True, max_length=18, verbose_name='CNPJ')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='e-mail de contato')),
                ('contact_phone', models.CharField(blank=True, max_length=20, verbose_name='telefone')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='excluido por')),
            ],
            options={
                'verbose_name': 'organizacao',
                'verbose_name_plural': 'organizacoes',
                'ordering': ['name'],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='ClinicMembership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='excluido')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='excluido em')),
                ('role', models.CharField(choices=[('superadmin', 'Superadministrador da plataforma'), ('clinic_admin', 'Administrador da clinica'), ('receptionist', 'Recepcionista'), ('professional', 'Profissional'), ('patient', 'Paciente')], default='receptionist', max_length=32, verbose_name='perfil')),
                ('extra_permissions', models.JSONField(blank=True, default=list, verbose_name='permissoes adicionais')),
                ('denied_permissions', models.JSONField(blank=True, default=list, verbose_name='permissoes negadas')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='ativo')),
                ('is_default', models.BooleanField(default=False, verbose_name='clinica padrao do usuario')),
                ('job_title', models.CharField(blank=True, max_length=80, verbose_name='cargo')),
                ('started_at', models.DateField(blank=True, null=True, verbose_name='inicio do vinculo')),
                ('ended_at', models.DateField(blank=True, null=True, verbose_name='fim do vinculo')),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='clinics.clinic', verbose_name='clinica')),
                ('custom_role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='memberships', to='accounts.role', verbose_name='papel personalizado')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='excluido por')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clinic_memberships', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'vinculo com clinica',
                'verbose_name_plural': 'vinculos com clinicas',
                'ordering': ['clinic__trade_name', 'user__full_name'],
                'indexes': [models.Index(fields=['user', 'is_active'], name='tenants_cli_user_id_dd09dc_idx'), models.Index(fields=['clinic', 'role'], name='tenants_cli_clinic__227b44_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('user', 'clinic'), name='uniq_active_membership_user_clinic')],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
