# Generated by Django 5.2.17 on 2026-08-24 23:05

import apps.core.storage
import apps.core.validators
import datetime
import django.db.models.deletion
import django.db.models.manager
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='excluido')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='excluido em')),
                ('primary_color', models.CharField(default='#0b5ed7', max_length=7, validators=[apps.core.validators.validate_hex_color], verbose_name='cor primaria')),
                ('secondary_color', models.CharField(default='#0dcaf0', max_length=7, validators=[apps.core.validators.validate_hex_color], verbose_name='cor secundaria')),
                ('appointment_duration', models.PositiveIntegerField(default=30, verbose_name='duracao padrao (min)')),
                ('opening_time', models.TimeField(default=datetime.time(8, 0), verbose_name='abertura')),
                ('closing_time', models.TimeField(default=datetime.time(18, 0), verbose_name='fechamento')),
                ('working_days', models.JSONField(blank=True, default=list, verbose_name='dias de funcionamento')),
                ('allow_overbooking', models.BooleanField(default=True, verbose_name='permitir encaixe')),
                ('allow_patient_scheduling', models.BooleanField(default=True, verbose_name='paciente pode solicitar agendamento')),
                ('patient_cancel_hours', models.PositiveIntegerField(default=24, verbose_name='antecedencia minima para cancelar (h)')),
                ('notify_email', models.BooleanField(default=True, verbose_name='notificar por e-mail')),
                ('notify_whatsapp', models.BooleanField(default=False, verbose_name='notificar por WhatsApp')),
                ('notify_sms', models.BooleanField(default=False, verbose_name='notificar por SMS')),
                ('reminder_hours_before', models.PositiveIntegerField(default=24, verbose_name='lembrete (h antes)')),
                ('record_lock_hours', models.PositiveIntegerField(default=24, verbose_name='prazo para editar registro assinado (h)')),
                ('require_photo_consent', models.BooleanField(default=True, verbose_name='exigir consentimento para fotos')),
                ('data_retention_years', models.PositiveIntegerField(default=20, verbose_name='retencao de prontuario (anos)')),
            ],
            options={
                'verbose_name': 'configuracao da clinica',
                'verbose_name_plural': 'configuracoes das clinicas',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='InsurancePlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='excluido')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='excluido em')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='ativo')),
                ('name', models.CharField(max_length=120, verbose_name='convenio')),
                ('registry_code', models.CharField(blank=True, max_length=40, verbose_name='registro ANS')),
                ('contact', models.CharField(blank=True, max_length=120, verbose_name='contato')),
                ('notes', models.TextField(blank=True, verbose_name='observacoes')),
            ],
            options={
                'verbose_name': 'convenio',
                'verbose_name_plural': 'convenios',
                'ordering': ['name'],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='excluido')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='excluido em')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='ativo')),
                ('name', models.CharField(max_length=80, verbose_name='nome')),
                ('identifier', models.CharField(blank=True, max_length=40, verbose_name='identificacao')),
                ('capacity', models.PositiveIntegerField(default=1, verbose_name='capacidade')),
                ('notes', models.CharField(blank=True, max_length=200, verbose_name='observacoes')),
            ],
            options={
                'verbose_name': 'sala',
                'verbose_name_plural': 'salas',
                'ordering': ['name'],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='excluido')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='excluido em')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='ativo')),
                ('name', models.CharField(max_length=140, verbose_name='nome')),
                ('code', models.CharField(blank=True, max_length=40, verbose_name='codigo interno')),
                ('duration_minutes', models.PositiveIntegerField(default=30, verbose_name='duracao (min)')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='valor')),
                ('requires_room', models.BooleanField(default=False, verbose_name='exige sala')),
                ('description', models.TextField(blank=True, verbose_name='descricao')),
            ],
            options={
                'verbose_name': 'servico',
                'verbose_name_plural': 'servicos',
                'ordering': ['name'],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='excluido')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='excluido em')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='ativo')),
                ('name', models.CharField(max_length=120, verbose_name='nome')),
                ('description', models.TextField(blank=True, verbose_name='descricao')),
                ('color', models.CharField(default='#6c757d', max_length=7, validators=[apps.core.validators.validate_hex_color], verbose_name='cor na agenda')),
            ],
            options={
                'verbose_name': 'especialidade',
                'verbose_name_plural': 'especialidades',
                'ordering': ['name'],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='excluido')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='excluido em')),
                ('legal_name', models.CharField(max_length=180, verbose_name='razao social')),
                ('trade_name', models.CharField(max_length=180, verbose_name='nome fantasia')),
                ('slug', models.SlugField(max_length=180, unique=True, verbose_name='identificador (slug)')),
                ('document', models.CharField(max_length=18, unique=True, validators=[apps.core.validators.validate_cpf_or_cnpj], verbose_name='CNPJ/CPF')),
                ('clinic_type', models.CharField(choices=[('medica', 'Clinica medica'), ('fisioterapia', 'Fisioterapia'), ('odontologica', 'Odontologica'), ('psicologia', 'Psicologia'), ('nutricao', 'Nutricao'), ('estetica', 'Estetica'), ('dermatologia', 'Dermatologia'), ('exames', 'Clinica de exames'), ('multidisciplinar', 'Multidisciplinar'), ('veterinaria', 'Veterinaria'), ('outro', 'Outro')], default='medica', max_length=32, verbose_name='tipo de clinica')),
                ('logo', models.ImageField(blank=True, null=True, upload_to=apps.core.storage.clinic_logo_path, validators=[apps.core.validators.UploadValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'], allowed_mime_types=['image/jpeg', 'image/png', 'image/webp'], max_size=8388608)], verbose_name='logotipo')),
                ('address', models.CharField(blank=True, max_length=180, verbose_name='logradouro')),
                ('address_number', models.CharField(blank=True, max_length=20, verbose_name='numero')),
                ('address_complement', models.CharField(blank=True, max_length=80, verbose_name='complemento')),
                ('district', models.CharField(blank=True, max_length=100, verbose_name='bairro')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='cidade')),
                ('state', models.CharField(blank=True, choices=[('AC', 'AC'), ('AL', 'AL'), ('AP', 'AP'), ('AM', 'AM'), ('BA', 'BA'), ('CE', 'CE'), ('DF', 'DF'), ('ES', 'ES'), ('GO', 'GO'), ('MA', 'MA'), ('MT', 'MT'), ('MS', 'MS'), ('MG', 'MG'), ('PA', 'PA'), ('PB', 'PB'), ('PR', 'PR'), ('PE', 'PE'), ('PI', 'PI'), ('RJ', 'RJ'), ('RN', 'RN'), ('RS', 'RS'), ('RO', 'RO'), ('RR', 'RR'), ('SC', 'SC'), ('SP', 'SP'), ('SE', 'SE'), ('TO', 'TO')], max_length=2, verbose_name='estado')),
                ('postal_code', models.CharField(blank=True, max_length=9, validators=[apps.core.validators.validate_cep], verbose_name='CEP')),
                ('phone', models.CharField(blank=True, max_length=20, validators=[apps.core.validators.validate_phone], verbose_name='telefone')),
                ('whatsapp', models.CharField(blank=True, max_length=20, verbose_name='WhatsApp')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='e-mail')),
                ('website', models.URLField(blank=True, verbose_name='site')),
                ('responsible_name', models.CharField(blank=True, max_length=180, verbose_name='responsavel')),
                ('responsible_document', models.CharField(blank=True, max_length=14, verbose_name='CPF do responsavel')),
                ('professional_registry', models.CharField(blank=True, max_length=40, verbose_name='registro profissional (CRM/CRO/CREFITO/CRP...)')),
                ('status', models.CharField(choices=[('active', 'Ativa'), ('trial', 'Em avaliacao'), ('suspended', 'Suspensa'), ('canceled', 'Cancelada')], db_index=True, default='trial', max_length=20, verbose_name='status')),
                ('modules', models.JSONField(blank=True, default=list, verbose_name='modulos habilitados')),
                ('notes', models.TextField(blank=True, verbose_name='observacoes internas')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='excluido por')),
            ],
            options={
                'verbose_name': 'clinica',
                'verbose_name_plural': 'clinicas',
                'ordering': ['trade_name'],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
