# Generated by Django 5.2.17 on 2026-08-24 23:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinics', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clinics', to='tenants.organization', verbose_name='organizacao'),
        ),
        migrations.AddField(
            model_name='clinicsettings',
            name='clinic',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='clinics.clinic', verbose_name='clinica'),
        ),
        migrations.AddField(
            model_name='clinicsettings',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='excluido por'),
        ),
        migrations.AddField(
            model_name='insuranceplan',
            name='clinic',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='clinics.clinic', verbose_name='clinica'),
        ),
        migrations.AddField(
            model_name='insuranceplan',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='excluido por'),
        ),
        migrations.AddField(
            model_name='room',
            name='clinic',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='clinics.clinic', verbose_name='clinica'),
        ),
        migrations.AddField(
            model_name='room',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='excluido por'),
        ),
        migrations.AddField(
            model_name='service',
            name='clinic',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='clinics.clinic', verbose_name='clinica'),
        ),
        migrations.AddField(
            model_name='service',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='excluido por'),
        ),
        migrations.AddField(
            model_name='specialty',
            name='clinic',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='clinics.clinic', verbose_name='clinica'),
        ),
        migrations.AddField(
            model_name='specialty',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='excluido por'),
        ),
        migrations.AddField(
            model_name='service',
            name='specialty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services', to='clinics.specialty', verbose_name='especialidade'),
        ),
        migrations.AddIndex(
            model_name='clinic',
            index=models.Index(fields=['status', 'clinic_type'], name='clinics_cli_status_f6752d_idx'),
        ),
        migrations.AddIndex(
            model_name='clinic',
            index=models.Index(fields=['slug'], name='clinics_cli_slug_c0ea0f_idx'),
        ),
        migrations.AddConstraint(
            model_name='insuranceplan',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('clinic', 'name'), name='uniq_insurance_per_clinic'),
        ),
        migrations.AddConstraint(
            model_name='room',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('clinic', 'name'), name='uniq_room_per_clinic'),
        ),
        migrations.AddConstraint(
            model_name='specialty',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('clinic', 'name'), name='uniq_specialty_per_clinic'),
        ),
        migrations.AddConstraint(
            model_name='service',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('clinic', 'name'), name='uniq_service_per_clinic'),
        ),
    ]
