# Generated by Django 5.2.17 on 2026-08-24 23:05

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='data/hora')),
                ('user_email', models.CharField(blank=True, max_length=254, verbose_name='e-mail (snapshot)')),
                ('user_role', models.CharField(blank=True, max_length=32, verbose_name='perfil')),
                ('clinic_name', models.CharField(blank=True, max_length=180, verbose_name='clinica (snapshot)')),
                ('action', models.CharField(choices=[('login', 'Login'), ('login_failed', 'Falha de login'), ('logout', 'Logout'), ('password_change', 'Alteracao de senha'), ('mfa_change', 'Alteracao de MFA'), ('create', 'Criacao'), ('update', 'Alteracao'), ('delete', 'Exclusao'), ('view', 'Visualizacao'), ('view_sensitive', 'Visualizacao de dado sensivel'), ('download', 'Download de documento'), ('upload', 'Upload de documento'), ('export', 'Exportacao de dados'), ('permission_change', 'Alteracao de permissoes'), ('settings_change', 'Alteracao de configuracoes'), ('access_denied', 'Acesso negado'), ('tenant_switch', 'Troca de clinica'), ('platform_access', 'Acesso administrativo global'), ('security_alert', 'Alerta de seguranca')], db_index=True, max_length=32, verbose_name='acao')),
                ('object_type', models.CharField(blank=True, db_index=True, max_length=120, verbose_name='tipo do objeto')),
                ('object_id', models.CharField(blank=True, db_index=True, max_length=64, verbose_name='id do objeto')),
                ('object_repr', models.CharField(blank=True, max_length=250, verbose_name='objeto')),
                ('description', models.TextField(blank=True, verbose_name='descricao')),
                ('changes', models.JSONField(blank=True, default=dict, verbose_name='alteracoes')),
                ('result', models.CharField(choices=[('success', 'Sucesso'), ('denied', 'Negado'), ('error', 'Erro')], default='success', max_length=16, verbose_name='resultado')),
                ('is_sensitive', models.BooleanField(db_index=True, default=False, verbose_name='dado sensivel')),
                ('ip_address', models.CharField(blank=True, max_length=45, verbose_name='IP')),
                ('user_agent', models.CharField(blank=True, max_length=400, verbose_name='user-agent')),
                ('path', models.CharField(blank=True, max_length=255, verbose_name='rota')),
                ('method', models.CharField(blank=True, max_length=10, verbose_name='metodo')),
                ('session_key', models.CharField(blank=True, max_length=64, verbose_name='sessao')),
                ('checksum', models.CharField(blank=True, editable=False, max_length=64)),
                ('previous_checksum', models.CharField(blank=True, editable=False, max_length=64)),
            ],
            options={
                'verbose_name': 'registro de auditoria',
                'verbose_name_plural': 'registros de auditoria',
                'ordering': ['-created_at'],
            },
        ),
    ]
