# Generated by Django 5.2.17 on 2026-08-24 23:05

import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='excluido')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='excluido em')),
                ('status', models.CharField(choices=[('trial', 'Avaliacao'), ('active', 'Ativa'), ('past_due', 'Em atraso'), ('canceled', 'Cancelada')], db_index=True, default='trial', max_length=20, verbose_name='status')),
                ('cycle', models.CharField(choices=[('monthly', 'Mensal'), ('yearly', 'Anual')], default='monthly', max_length=20, verbose_name='ciclo')),
                ('started_at', models.DateField(default=django.utils.timezone.localdate, verbose_name='inicio')),
                ('trial_ends_at', models.DateField(blank=True, null=True, verbose_name='fim da avaliacao')),
                ('current_period_start', models.DateField(blank=True, null=True, verbose_name='inicio do periodo')),
                ('current_period_end', models.DateField(blank=True, null=True, verbose_name='fim do periodo')),
                ('canceled_at', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, verbose_name='observacoes')),
            ],
            options={
                'verbose_name': 'assinatura',
                'verbose_name_plural': 'assinaturas',
                'ordering': ['-created_at'],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='excluido')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='excluido em')),
                ('number', models.CharField(max_length=20, unique=True, verbose_name='numero')),
                ('reference_month', models.DateField(verbose_name='competencia')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='valor')),
                ('due_date', models.DateField(verbose_name='vencimento')),
                ('status', models.CharField(choices=[('open', 'Em aberto'), ('paid', 'Paga'), ('overdue', 'Vencida'), ('canceled', 'Cancelada')], db_index=True, default='open', max_length=20, verbose_name='status')),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=250, verbose_name='observacoes')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='excluido por')),
            ],
            options={
                'verbose_name': 'fatura',
                'verbose_name_plural': 'faturas',
                'ordering': ['-reference_month'],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='excluido')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='excluido em')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='valor')),
                ('method', models.CharField(choices=[('pix', 'PIX'), ('boleto', 'Boleto'), ('card', 'Cartao'), ('transfer', 'Transferencia'), ('manual', 'Baixa manual')], default='manual', max_length=20, verbose_name='forma')),
                ('paid_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='pago em')),
                ('gateway', models.CharField(blank=True, max_length=40, verbose_name='gateway')),
                ('external_id', models.CharField(blank=True, max_length=120, verbose_name='id externo')),
                ('receipt', models.CharField(blank=True, max_length=180, verbose_name='comprovante')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='excluido por')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='billing.invoice')),
            ],
            options={
                'verbose_name': 'pagamento',
                'verbose_name_plural': 'pagamentos',
                'ordering': ['-paid_at'],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='excluido')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='excluido em')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='ativo')),
                ('name', models.CharField(max_length=80, unique=True, verbose_name='nome')),
                ('tier', models.CharField(choices=[('basic', 'Basico'), ('professional', 'Profissional'), ('premium', 'Premium'), ('enterprise', 'Enterprise')], default='basic', max_length=20, verbose_name='nivel')),
                ('description', models.TextField(blank=True, verbose_name='descricao')),
                ('monthly_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='mensalidade')),
                ('yearly_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='anuidade')),
                ('max_professionals', models.PositiveIntegerField(default=3, verbose_name='limite de profissionais')),
                ('max_users', models.PositiveIntegerField(default=5, verbose_name='limite de usuarios')),
                ('max_patients', models.PositiveIntegerField(default=500, verbose_name='limite de pacientes')),
                ('max_storage_mb', models.PositiveIntegerField(default=2048, verbose_name='armazenamento (MB)')),
                ('max_clinics', models.PositiveIntegerField(default=1, verbose_name='clinicas por organizacao')),
                ('modules', models.JSONField(blank=True, default=list, verbose_name='modulos incluidos')),
                ('supports_api', models.BooleanField(default=False, verbose_name='acesso a API')),
                ('supports_mfa', models.BooleanField(default=True, verbose_name='MFA obrigatorio disponivel')),
                ('priority_support', models.BooleanField(default=False, verbose_name='suporte prioritario')),
                ('trial_days', models.PositiveIntegerField(default=14, verbose_name='dias de avaliacao')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='excluido por')),
            ],
            options={
                'verbose_name': 'plano',
                'verbose_name_plural': 'planos',
                'ordering': ['monthly_price'],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
