# Generated by Django 5.2.17 on 2026-08-25 16:14

import django.db.models.deletion
import django.db.models.manager
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemExpense',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='excluido')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='excluido em')),
                ('category', models.CharField(choices=[('infrastructure', 'Infraestrutura/servidores'), ('payroll', 'Folha de pagamento'), ('marketing', 'Marketing'), ('software', 'Ferramentas e licencas'), ('support', 'Suporte'), ('taxes', 'Impostos'), ('other', 'Outros')], default='other', max_length=20, verbose_name='categoria')),
                ('description', models.CharField(max_length=200, verbose_name='descricao')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='valor')),
                ('expense_date', models.DateField(verbose_name='data')),
                ('is_recurring', models.BooleanField(default=False, verbose_name='recorrente')),
                ('notes', models.TextField(blank=True, verbose_name='observacoes')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='excluido por')),
            ],
            options={
                'verbose_name': 'despesa do sistema',
                'verbose_name_plural': 'despesas do sistema',
                'ordering': ['-expense_date'],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
