# Generated by Django 5.2.17 on 2026-08-27 07:00

import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinics', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='excluido')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='excluido em')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='ativo')),
                ('name', models.CharField(max_length=160, verbose_name='nome')),
                ('sku', models.CharField(blank=True, max_length=60, verbose_name='codigo/SKU')),
                ('unit', models.CharField(default='un', max_length=20, verbose_name='unidade')),
                ('category', models.CharField(blank=True, max_length=80, verbose_name='categoria')),
                ('minimum_stock', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='estoque minimo')),
                ('current_stock', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='estoque atual')),
                ('cost_price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='preco de custo')),
                ('sale_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='preco de venda')),
                ('notes', models.TextField(blank=True, verbose_name='observacoes')),
                ('clinic', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='clinics.clinic', verbose_name='clinica')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='excluido por')),
            ],
            options={
                'verbose_name': 'produto',
                'verbose_name_plural': 'produtos',
                'ordering': ['name'],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='excluido')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='excluido em')),
                ('kind', models.CharField(choices=[('entry', 'Entrada'), ('exit', 'Saida')], max_length=10, verbose_name='tipo')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='quantidade')),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='custo unitario')),
                ('reason', models.CharField(blank=True, max_length=160, verbose_name='motivo')),
                ('notes', models.TextField(blank=True, verbose_name='observacoes')),
                ('moved_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='data/hora')),
                ('clinic', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='clinics.clinic', verbose_name='clinica')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='registrado por')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='excluido por')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='inventory.product', verbose_name='produto')),
            ],
            options={
                'verbose_name': 'movimentacao de estoque',
                'verbose_name_plural': 'movimentacoes de estoque',
                'ordering': ['-moved_at'],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False), models.Q(('sku', ''), _negated=True)), fields=('clinic', 'sku'), name='uniq_product_sku_per_clinic'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['clinic', '-moved_at'], name='inventory_s_clinic__7776e2_idx'),
        ),
    ]
