# Generated by Django 5.2.17 on 2026-08-24 23:05

import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinics', '0002_initial'),
        ('documents', '0001_initial'),
        ('medical_records', '0001_initial'),
        ('patients', '0001_initial'),
        ('professionals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Examination',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='excluido')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='excluido em')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='ativo')),
                ('name', models.CharField(max_length=160, verbose_name='exame')),
                ('code', models.CharField(blank=True, max_length=40, verbose_name='codigo (TUSS/interno)')),
                ('category', models.CharField(blank=True, max_length=80, verbose_name='categoria')),
                ('preparation', models.TextField(blank=True, verbose_name='preparo')),
                ('clinic', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='clinics.clinic', verbose_name='clinica')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='excluido por')),
            ],
            options={
                'verbose_name': 'exame (catalogo)',
                'verbose_name_plural': 'exames (catalogo)',
                'ordering': ['name'],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='ExaminationRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='excluido')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='excluido em')),
                ('number', models.PositiveIntegerField(db_index=True, editable=False, verbose_name='numero')),
                ('clinical_indication', models.TextField(verbose_name='indicacao/justificativa clinica')),
                ('observations', models.TextField(blank=True, verbose_name='observacoes')),
                ('priority', models.CharField(choices=[('routine', 'Rotina'), ('priority', 'Prioritario'), ('urgent', 'Urgente')], default='routine', max_length=20, verbose_name='prioridade')),
                ('status', models.CharField(choices=[('requested', 'Solicitado'), ('collected', 'Coletado/realizado'), ('partial', 'Resultado parcial'), ('completed', 'Concluido'), ('canceled', 'Cancelado')], db_index=True, default='requested', max_length=20, verbose_name='status')),
                ('requested_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='solicitado em')),
                ('released_to_patient', models.BooleanField(default=True, verbose_name='liberado no portal')),
                ('signature_hash', models.CharField(blank=True, editable=False, max_length=64)),
                ('clinic', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='clinics.clinic', verbose_name='clinica')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='excluido por')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examination_requests', to='patients.patient', verbose_name='paciente')),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='examination_requests', to='professionals.professional', verbose_name='solicitante')),
                ('record_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='examination_requests', to='medical_records.medicalrecordentry', verbose_name='atendimento')),
            ],
            options={
                'verbose_name': 'solicitacao de exame',
                'verbose_name_plural': 'solicitacoes de exame',
                'ordering': ['-requested_at'],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='ExaminationRequestItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='excluido')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='excluido em')),
                ('name', models.CharField(max_length=160, verbose_name='exame')),
                ('quantity', models.PositiveSmallIntegerField(default=1, verbose_name='quantidade')),
                ('notes', models.CharField(blank=True, max_length=200, verbose_name='observacao')),
                ('clinic', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='clinics.clinic', verbose_name='clinica')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='excluido por')),
                ('examination', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='request_items', to='examinations.examination')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='examinations.examinationrequest')),
            ],
            options={
                'verbose_name': 'item da solicitacao',
                'verbose_name_plural': 'itens da solicitacao',
                'ordering': ['name'],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='ExaminationResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='excluido')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='excluido em')),
                ('summary', models.TextField(blank=True, verbose_name='resumo/laudo')),
                ('result_date', models.DateField(blank=True, null=True, verbose_name='data do resultado')),
                ('is_abnormal', models.BooleanField(default=False, verbose_name='resultado alterado')),
                ('released_to_patient', models.BooleanField(default=False, verbose_name='liberado ao paciente')),
                ('clinic', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='clinics.clinic', verbose_name='clinica')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='excluido por')),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='examination_results', to='documents.document', verbose_name='arquivo do resultado')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='results', to='examinations.examinationrequestitem')),
                ('registered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='examinations.examinationrequest')),
            ],
            options={
                'verbose_name': 'resultado de exame',
                'verbose_name_plural': 'resultados de exame',
                'ordering': ['-created_at'],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddConstraint(
            model_name='examination',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('clinic', 'name'), name='uniq_examination_per_clinic'),
        ),
        migrations.AddIndex(
            model_name='examinationrequest',
            index=models.Index(fields=['clinic', '-requested_at'], name='examination_clinic__3675e4_idx'),
        ),
        migrations.AddConstraint(
            model_name='examinationrequest',
            constraint=models.UniqueConstraint(fields=('clinic', 'number'), name='uniq_examination_request_number_per_clinic'),
        ),
    ]
