# Generated by Django 5.2.17 on 2026-08-26 09:59

import django.db.models.deletion
import django.db.models.manager
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinics', '0002_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Automation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='excluido')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='excluido em')),
                ('codename', models.CharField(db_index=True, max_length=80, unique=True, verbose_name='codigo')),
                ('name', models.CharField(max_length=120, verbose_name='nome')),
                ('layer', models.CharField(choices=[('operational', 'Operacional'), ('communication', 'Comunicacao'), ('management', 'Gestao'), ('intelligence', 'Inteligencia'), ('ai', 'Inteligencia artificial')], max_length=20, verbose_name='camada')),
                ('description', models.CharField(blank=True, max_length=250, verbose_name='descricao')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='excluido por')),
            ],
            options={
                'verbose_name': 'automacao',
                'verbose_name_plural': 'automacoes',
                'ordering': ['layer', 'name'],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='AutomationSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='excluido')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='excluido em')),
                ('waiting_list_auto_invite', models.BooleanField(default=True, help_text='Ao cancelar um agendamento, avisa a recepcao se houver paciente compativel aguardando na lista de espera.', verbose_name='convidar lista de espera automaticamente')),
                ('auto_generate_receipt', models.BooleanField(default=True, verbose_name='gerar comprovante de pagamento automaticamente')),
                ('financial_webhook_enabled', models.BooleanField(default=False, help_text='So ative apos configurar a integracao com um provedor de pagamentos.', verbose_name='aceitar baixa automatica via webhook financeiro')),
                ('financial_webhook_secret', models.CharField(blank=True, editable=False, max_length=64, verbose_name='segredo do webhook financeiro')),
                ('clinic', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='automation_settings', to='clinics.clinic', verbose_name='clinica')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='excluido por')),
            ],
            options={
                'verbose_name': 'configuracao de automacao',
                'verbose_name_plural': 'configuracoes de automacao',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='AutomationExecution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='excluido')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='excluido em')),
                ('idempotency_key', models.CharField(db_index=True, max_length=200, verbose_name='chave de idempotencia')),
                ('status', models.CharField(choices=[('pending', 'Em andamento'), ('success', 'Sucesso'), ('skipped', 'Ignorada (condicao nao atendida)'), ('failed', 'Falhou')], db_index=True, default='pending', max_length=10, verbose_name='status')),
                ('trigger_object_id', models.CharField(blank=True, max_length=64)),
                ('attempts', models.PositiveSmallIntegerField(default=0, verbose_name='tentativas')),
                ('last_error', models.TextField(blank=True, verbose_name='ultimo erro')),
                ('result', models.JSONField(blank=True, default=dict, verbose_name='resultado')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='iniciado em')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='finalizado em')),
                ('automation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='executions', to='automation.automation', verbose_name='automacao')),
                ('clinic', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='clinics.clinic', verbose_name='clinica')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='excluido por')),
                ('trigger_content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='contenttypes.contenttype', verbose_name='tipo do objeto que disparou')),
            ],
            options={
                'verbose_name': 'execucao de automacao',
                'verbose_name_plural': 'execucoes de automacao',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['clinic', '-started_at'], name='automation__clinic__5b3596_idx'), models.Index(fields=['clinic', 'automation', 'status'], name='automation__clinic__12749e_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'success')), fields=('clinic', 'automation', 'idempotency_key'), name='uniq_automation_execution_success')],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
