# Generated by Django 5.2.17 on 2026-08-24 23:05

import apps.core.storage
import apps.core.validators
import django.db.models.deletion
import django.db.models.manager
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinics', '0002_initial'),
        ('medical_records', '0001_initial'),
        ('patients', '0001_initial'),
        ('scheduling', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='excluido')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='excluido em')),
                ('title', models.CharField(max_length=180, verbose_name='titulo')),
                ('description', models.TextField(blank=True, verbose_name='descricao')),
                ('file', models.FileField(storage=apps.core.storage.PrivateMediaStorage(), upload_to=apps.core.storage.private_upload_path, validators=[apps.core.validators.UploadValidator()], verbose_name='arquivo')),
                ('original_name', models.CharField(blank=True, editable=False, max_length=180, verbose_name='nome original')),
                ('content_type', models.CharField(blank=True, editable=False, max_length=100, verbose_name='tipo MIME')),
                ('size', models.PositiveBigIntegerField(default=0, editable=False, verbose_name='tamanho (bytes)')),
                ('checksum', models.CharField(blank=True, editable=False, max_length=64, verbose_name='SHA-256')),
                ('is_sensitive', models.BooleanField(default=True, verbose_name='dado sensivel de saude')),
                ('visible_to_patient', models.BooleanField(default=False, verbose_name='liberado no portal do paciente')),
                ('requires_consent', models.BooleanField(default=False, verbose_name='exige consentimento registrado')),
                ('issued_at', models.DateField(blank=True, null=True, verbose_name='data do documento')),
                ('download_count', models.PositiveIntegerField(default=0, editable=False)),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='scheduling.appointment', verbose_name='agendamento')),
                ('clinic', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='clinics.clinic', verbose_name='clinica')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='excluido por')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='patients.patient', verbose_name='paciente')),
                ('record_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='medical_records.medicalrecordentry', verbose_name='atendimento')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL, verbose_name='enviado por')),
            ],
            options={
                'verbose_name': 'documento',
                'verbose_name_plural': 'documentos',
                'ordering': ['-created_at'],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='DocumentAccessLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='excluido')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='excluido em')),
                ('ip_address', models.CharField(blank=True, max_length=45)),
                ('action', models.CharField(choices=[('view', 'Visualizacao'), ('download', 'Download')], default='download', max_length=20)),
                ('clinic', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='clinics.clinic', verbose_name='clinica')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='excluido por')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_logs', to='documents.document')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'acesso a documento',
                'verbose_name_plural': 'acessos a documentos',
                'ordering': ['-created_at'],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='DocumentCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='excluido')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='excluido em')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='ativo')),
                ('name', models.CharField(max_length=80, verbose_name='nome')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='descricao')),
                ('is_clinical', models.BooleanField(default=True, help_text='Documentos clinicos exigem permissao assistencial para leitura.', verbose_name='conteudo clinico')),
                ('visible_to_patient_default', models.BooleanField(default=False, verbose_name='visivel ao paciente por padrao')),
                ('clinic', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='clinics.clinic', verbose_name='clinica')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='excluido por')),
            ],
            options={
                'verbose_name': 'categoria de documento',
                'verbose_name_plural': 'categorias de documento',
                'ordering': ['name'],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='document',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='documents.documentcategory', verbose_name='categoria'),
        ),
        migrations.AddConstraint(
            model_name='documentcategory',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('clinic', 'name'), name='uniq_document_category_per_clinic'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['clinic', '-created_at'], name='documents_d_clinic__f2feb3_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['patient', '-created_at'], name='documents_d_patient_de27de_idx'),
        ),
    ]
