# Generated by Django 5.2.17 on 2026-08-24 23:05

import apps.core.validators
import django.db.models.deletion
import django.db.models.manager
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Professional',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='excluido')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='excluido em')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='ativo')),
                ('full_name', models.CharField(db_index=True, max_length=180, verbose_name='nome completo')),
                ('social_name', models.CharField(blank=True, max_length=180, verbose_name='nome de tratamento')),
                ('cpf', models.CharField(blank=True, max_length=14, validators=[apps.core.validators.validate_cpf], verbose_name='CPF')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='data de nascimento')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='e-mail')),
                ('phone', models.CharField(blank=True, max_length=20, validators=[apps.core.validators.validate_phone], verbose_name='telefone')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='professionals/photos/', verbose_name='foto')),
                ('council', models.CharField(blank=True, choices=[('CRM', 'CRM - Medicina'), ('CRO', 'CRO - Odontologia'), ('CREFITO', 'CREFITO - Fisioterapia'), ('CRP', 'CRP - Psicologia'), ('CRN', 'CRN - Nutricao'), ('COREN', 'COREN - Enfermagem'), ('CRBM', 'CRBM - Biomedicina'), ('CRMV', 'CRMV - Medicina Veterinaria'), ('CREF', 'CREF - Educacao Fisica'), ('OUTRO', 'Outro')], max_length=20, verbose_name='conselho')),
                ('registry_number', models.CharField(blank=True, max_length=40, verbose_name='registro profissional')),
                ('registry_state', models.CharField(blank=True, max_length=2, verbose_name='UF do registro')),
                ('subspecialty', models.CharField(blank=True, max_length=120, verbose_name='subespecialidade')),
                ('biography', models.TextField(blank=True, verbose_name='biografia')),
                ('appointment_duration', models.PositiveIntegerField(default=30, verbose_name='duracao padrao (min)')),
                ('accepts_online_scheduling', models.BooleanField(default=True, verbose_name='aceita solicitacao pelo portal do paciente')),
                ('notes', models.TextField(blank=True, verbose_name='observacoes internas')),
                ('clinic', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='clinics.clinic', verbose_name='clinica')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='excluido por')),
                ('rooms', models.ManyToManyField(blank=True, related_name='professionals', to='clinics.room', verbose_name='salas')),
                ('services', models.ManyToManyField(blank=True, related_name='professionals', to='clinics.service', verbose_name='servicos realizados')),
                ('specialties', models.ManyToManyField(blank=True, related_name='professionals', to='clinics.specialty', verbose_name='especialidades')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='professional_profiles', to=settings.AUTH_USER_MODEL, verbose_name='usuario de acesso')),
            ],
            options={
                'verbose_name': 'profissional',
                'verbose_name_plural': 'profissionais',
                'ordering': ['full_name'],
                'indexes': [models.Index(fields=['clinic', 'is_active'], name='professiona_clinic__d3e1ef_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_deleted', False), ('user__isnull', False)), fields=('clinic', 'user'), name='uniq_professional_user_per_clinic')],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
