# Generated by Django 5.2.17 on 2026-08-27 07:00

import apps.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professionals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='professional',
            name='address',
            field=models.CharField(blank=True, max_length=180, verbose_name='logradouro'),
        ),
        migrations.AddField(
            model_name='professional',
            name='address_complement',
            field=models.CharField(blank=True, max_length=80, verbose_name='complemento'),
        ),
        migrations.AddField(
            model_name='professional',
            name='address_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='numero'),
        ),
        migrations.AddField(
            model_name='professional',
            name='city',
            field=models.CharField(blank=True, max_length=100, verbose_name='cidade'),
        ),
        migrations.AddField(
            model_name='professional',
            name='district',
            field=models.CharField(blank=True, max_length=100, verbose_name='bairro'),
        ),
        migrations.AddField(
            model_name='professional',
            name='postal_code',
            field=models.CharField(blank=True, max_length=9, validators=[apps.core.validators.validate_cep], verbose_name='CEP'),
        ),
        migrations.AddField(
            model_name='professional',
            name='state',
            field=models.CharField(blank=True, max_length=2, verbose_name='estado'),
        ),
    ]
