# Generated by Django 5.2.17 on 2026-08-24 23:05

import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinics', '0002_initial'),
        ('documents', '0001_initial'),
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsentType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='excluido')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='excluido em')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='ativo')),
                ('name', models.CharField(max_length=140, verbose_name='nome')),
                ('description', models.TextField(blank=True, verbose_name='descricao')),
                ('content', models.TextField(verbose_name='texto do termo')),
                ('legal_basis', models.CharField(choices=[('consent', 'Consentimento (art. 7, I / art. 11, I)'), ('legal_obligation', 'Cumprimento de obrigacao legal (art. 7, II)'), ('contract', 'Execucao de contrato (art. 7, V)'), ('health_protection', 'Tutela da saude (art. 7, VIII / art. 11, II, f)'), ('legitimate_interest', 'Legitimo interesse (art. 7, IX)'), ('rights_defense', 'Exercicio regular de direitos (art. 7, VI)')], default='consent', max_length=32, verbose_name='base legal')),
                ('is_required', models.BooleanField(default=False, verbose_name='obrigatorio para atendimento')),
                ('version', models.CharField(default='1.0', max_length=20, verbose_name='versao')),
                ('clinic', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='clinics.clinic', verbose_name='clinica')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='excluido por')),
            ],
            options={
                'verbose_name': 'tipo de consentimento',
                'verbose_name_plural': 'tipos de consentimento',
                'ordering': ['name'],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Consent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='excluido')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='excluido em')),
                ('granted', models.BooleanField(default=True, verbose_name='concedido')),
                ('granted_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='data do aceite')),
                ('revoked_at', models.DateTimeField(blank=True, null=True, verbose_name='revogado em')),
                ('revocation_reason', models.CharField(blank=True, max_length=250, verbose_name='motivo da revogacao')),
                ('channel', models.CharField(choices=[('in_person', 'Presencial'), ('portal', 'Portal do paciente'), ('document', 'Documento assinado')], default='in_person', max_length=20, verbose_name='canal de coleta')),
                ('ip_address', models.CharField(blank=True, max_length=45)),
                ('content_snapshot', models.TextField(blank=True, verbose_name='texto aceito (snapshot)')),
                ('clinic', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='clinics.clinic', verbose_name='clinica')),
                ('collected_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='excluido por')),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='documents.document')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consents', to='patients.patient', verbose_name='paciente')),
                ('consent_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consents', to='lgpd.consenttype', verbose_name='tipo')),
            ],
            options={
                'verbose_name': 'consentimento',
                'verbose_name_plural': 'consentimentos',
                'ordering': ['-granted_at'],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='DataSubjectRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='excluido')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='excluido em')),
                ('requester_name', models.CharField(max_length=180, verbose_name='titular')),
                ('requester_email', models.EmailField(max_length=254, verbose_name='e-mail para resposta')),
                ('kind', models.CharField(choices=[('access', 'Acesso aos dados'), ('correction', 'Correcao de dados'), ('portability', 'Portabilidade'), ('deletion', 'Eliminacao'), ('anonymization', 'Anonimizacao'), ('revoke_consent', 'Revogacao de consentimento'), ('information', 'Informacao sobre compartilhamento')], max_length=32, verbose_name='tipo')),
                ('description', models.TextField(blank=True, verbose_name='descricao do pedido')),
                ('status', models.CharField(choices=[('received', 'Recebida'), ('in_progress', 'Em analise'), ('completed', 'Concluida'), ('rejected', 'Recusada')], db_index=True, default='received', max_length=20, verbose_name='status')),
                ('response', models.TextField(blank=True, verbose_name='resposta')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='prazo de resposta')),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('clinic', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='clinics.clinic', verbose_name='clinica')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='excluido por')),
                ('handled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='data_requests', to='patients.patient')),
                ('requester', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='data_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'solicitacao do titular',
                'verbose_name_plural': 'solicitacoes do titular',
                'ordering': ['-created_at'],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='SecurityIncident',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='excluido')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='excluido em')),
                ('title', models.CharField(max_length=180, verbose_name='titulo')),
                ('description', models.TextField(verbose_name='descricao')),
                ('severity', models.CharField(choices=[('low', 'Baixa'), ('medium', 'Media'), ('high', 'Alta'), ('critical', 'Critica')], default='medium', max_length=20, verbose_name='severidade')),
                ('status', models.CharField(choices=[('open', 'Em apuracao'), ('contained', 'Contido'), ('notified', 'Comunicado a ANPD/titulares'), ('closed', 'Encerrado')], default='open', max_length=20, verbose_name='status')),
                ('detected_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='detectado em')),
                ('affected_records', models.PositiveIntegerField(default=0, verbose_name='registros afetados (estimativa)')),
                ('contains_sensitive_data', models.BooleanField(default=True, verbose_name='envolve dados sensiveis')),
                ('measures_taken', models.TextField(blank=True, verbose_name='medidas adotadas')),
                ('anpd_notified_at', models.DateTimeField(blank=True, null=True, verbose_name='comunicado a ANPD em')),
                ('subjects_notified_at', models.DateTimeField(blank=True, null=True, verbose_name='titulares comunicados em')),
                ('clinic', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='clinics.clinic', verbose_name='clinica')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='excluido por')),
                ('reported_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'incidente de seguranca',
                'verbose_name_plural': 'incidentes de seguranca',
                'ordering': ['-detected_at'],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddConstraint(
            model_name='consenttype',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('clinic', 'name', 'version'), name='uniq_consent_type_version_per_clinic'),
        ),
        migrations.AddIndex(
            model_name='consent',
            index=models.Index(fields=['clinic', 'patient', '-granted_at'], name='lgpd_consen_clinic__db77a7_idx'),
        ),
    ]
