# Generated by Django 5.2.17 on 2026-09-02 18:10

import django.db.models.deletion
import django.db.models.manager
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinics', '0002_initial'),
        ('scheduling', '0003_scheduletemplate_max_appointments'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CallPanelConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='excluido')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='excluido em')),
                ('ticket_prefix', models.CharField(default='A', max_length=3, verbose_name='prefixo da senha')),
                ('display_mode', models.CharField(choices=[('ticket_only', 'Somente a senha'), ('initials', 'Iniciais do paciente'), ('full_name', 'Nome completo')], default='ticket_only', max_length=12, verbose_name='exibicao no painel')),
                ('sound_enabled', models.BooleanField(default=True, verbose_name='som no painel')),
                ('no_show_minutes', models.PositiveIntegerField(default=15, verbose_name='minutos para alerta de nao comparecimento')),
                ('clinic', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='calling_config', to='clinics.clinic', verbose_name='clinica')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='excluido por')),
            ],
            options={
                'verbose_name': 'configuracao de chamada',
                'verbose_name_plural': 'configuracoes de chamada',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='CallTicket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='excluido')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='excluido em')),
                ('ticket_number', models.CharField(db_index=True, max_length=10, verbose_name='senha')),
                ('priority', models.CharField(choices=[('normal', 'Normal'), ('legal', 'Prioridade legal'), ('elderly', 'Idoso'), ('pregnant', 'Gestante'), ('pcd', 'PCD'), ('emergency', 'Emergencia')], default='normal', max_length=12, verbose_name='prioridade')),
                ('access_token', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='token de acesso')),
                ('token_expires_at', models.DateTimeField(verbose_name='token expira em')),
                ('call_count', models.PositiveIntegerField(default=0, verbose_name='vezes chamado')),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='call_ticket', to='scheduling.appointment', verbose_name='agendamento')),
                ('clinic', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='clinics.clinic', verbose_name='clinica')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='excluido por')),
            ],
            options={
                'verbose_name': 'senha de atendimento',
                'verbose_name_plural': 'senhas de atendimento',
                'ordering': ['-created_at'],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='CallEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='excluido')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='excluido em')),
                ('kind', models.CharField(choices=[('called', 'Chamado'), ('recalled', 'Rechamado')], max_length=10, verbose_name='tipo')),
                ('clinic', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='clinics.clinic', verbose_name='clinica')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='registrado por')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='excluido por')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='calling.callticket')),
            ],
            options={
                'verbose_name': 'evento de chamada',
                'verbose_name_plural': 'eventos de chamada',
                'ordering': ['-created_at'],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='PushSubscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='excluido')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='excluido em')),
                ('endpoint', models.URLField(max_length=500, unique=True, verbose_name='endpoint')),
                ('p256dh', models.CharField(max_length=255, verbose_name='chave p256dh')),
                ('auth', models.CharField(max_length=255, verbose_name='chave auth')),
                ('user_agent', models.CharField(blank=True, max_length=255, verbose_name='user agent')),
                ('clinic', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='clinics.clinic', verbose_name='clinica')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='excluido por')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_subscriptions', to='calling.callticket')),
            ],
            options={
                'verbose_name': 'inscricao de push',
                'verbose_name_plural': 'inscricoes de push',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddIndex(
            model_name='callticket',
            index=models.Index(fields=['clinic', 'created_at'], name='calling_cal_clinic__5df511_idx'),
        ),
    ]
