# Generated by Django 5.2.17 on 2026-09-07 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calling', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='callpanelconfig',
            name='highlight_seconds',
            field=models.PositiveIntegerField(default=20, verbose_name='duracao do destaque no painel de TV (segundos)'),
        ),
        migrations.AddField(
            model_name='callpanelconfig',
            name='voice_announcement',
            field=models.BooleanField(default=True, verbose_name='anunciar a chamada por voz'),
        ),
        migrations.AlterField(
            model_name='callpanelconfig',
            name='display_mode',
            field=models.CharField(choices=[('ticket_only', 'Somente a senha'), ('initials', 'Iniciais do paciente'), ('full_name', 'Nome completo')], default='full_name', max_length=12, verbose_name='exibicao no painel'),
        ),
    ]
