# Generated by Django 5.2.17 on 2026-08-24 23:05

import django.db.models.deletion
import django.db.models.manager
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='excluido')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='excluido em')),
                ('event', models.CharField(choices=[('appointment_created', 'Novo agendamento'), ('appointment_canceled', 'Agendamento cancelado'), ('appointment_rescheduled', 'Agendamento remarcado'), ('appointment_confirmed', 'Agendamento confirmado'), ('appointment_reminder', 'Lembrete de atendimento'), ('document_available', 'Novo documento disponivel'), ('exam_result', 'Resultado de exame'), ('record_pending', 'Prontuario pendente'), ('message', 'Mensagem'), ('security', 'Alerta de seguranca'), ('system', 'Aviso do sistema')], default='system', max_length=32, verbose_name='evento')),
                ('title', models.CharField(max_length=140, verbose_name='titulo')),
                ('message', models.TextField(blank=True, verbose_name='mensagem')),
                ('url', models.CharField(blank=True, max_length=255, verbose_name='link')),
                ('read_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='lida em')),
                ('level', models.CharField(choices=[('info', 'Informacao'), ('success', 'Sucesso'), ('warning', 'Atencao'), ('danger', 'Critico')], default='info', max_length=20, verbose_name='nivel')),
                ('clinic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='clinics.clinic', verbose_name='clinica')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='excluido por')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='destinatario')),
            ],
            options={
                'verbose_name': 'notificacao',
                'verbose_name_plural': 'notificacoes',
                'ordering': ['-created_at'],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='NotificationDelivery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='excluido')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='excluido em')),
                ('channel', models.CharField(choices=[('email', 'E-mail'), ('whatsapp', 'WhatsApp'), ('sms', 'SMS'), ('push', 'Push')], max_length=20, verbose_name='canal')),
                ('destination', models.CharField(max_length=180, verbose_name='destino')),
                ('subject', models.CharField(blank=True, max_length=180, verbose_name='assunto')),
                ('body', models.TextField(verbose_name='conteudo')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('sent', 'Enviado'), ('failed', 'Falhou'), ('skipped', 'Ignorado')], db_index=True, default='pending', max_length=20, verbose_name='status')),
                ('attempts', models.PositiveSmallIntegerField(default=0, verbose_name='tentativas')),
                ('error_message', models.CharField(blank=True, max_length=250, verbose_name='erro')),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('scheduled_for', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='agendado para')),
                ('clinic', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='clinics.clinic', verbose_name='clinica')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='excluido por')),
                ('notification', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='notifications.notification')),
            ],
            options={
                'verbose_name': 'envio de notificacao',
                'verbose_name_plural': 'envios de notificacao',
                'ordering': ['-created_at'],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', 'read_at', '-created_at'], name='notificatio_recipie_ce9d56_idx'),
        ),
    ]
