# Generated by Django 5.2.17 on 2026-08-24 23:05

import apps.accounts.models
import apps.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiToken',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80, verbose_name='descricao')),
                ('key_hash', models.CharField(editable=False, max_length=128, unique=True)),
                ('prefix', models.CharField(editable=False, max_length=12)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'token de API',
                'verbose_name_plural': 'tokens de API',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LoginAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.CharField(db_index=True, max_length=254)),
                ('successful', models.BooleanField(db_index=True, default=False)),
                ('ip_address', models.CharField(blank=True, max_length=45)),
                ('user_agent', models.CharField(blank=True, max_length=400)),
                ('reason', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'tentativa de login',
                'verbose_name_plural': 'tentativas de login',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80, verbose_name='nome')),
                ('base_role', models.CharField(choices=[('superadmin', 'Superadministrador da plataforma'), ('clinic_admin', 'Administrador da clinica'), ('receptionist', 'Recepcionista'), ('professional', 'Profissional'), ('patient', 'Paciente')], default='receptionist', max_length=32, verbose_name='perfil base')),
                ('permissions', models.JSONField(blank=True, default=list, verbose_name='permissoes')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('description', models.TextField(blank=True, verbose_name='descricao')),
            ],
            options={
                'verbose_name': 'papel',
                'verbose_name_plural': 'papeis',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_key', models.CharField(db_index=True, max_length=64)),
                ('ip_address', models.CharField(blank=True, max_length=45)),
                ('user_agent', models.CharField(blank=True, max_length=400)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'sessao',
                'verbose_name_plural': 'sessoes',
                'ordering': ['-last_activity'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True, verbose_name='e-mail')),
                ('full_name', models.CharField(max_length=180, verbose_name='nome completo')),
                ('cpf', models.CharField(blank=True, db_index=True, max_length=14, validators=[apps.core.validators.validate_cpf], verbose_name='CPF')),
                ('phone', models.CharField(blank=True, max_length=20, validators=[apps.core.validators.validate_phone], verbose_name='telefone')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='data de nascimento')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='foto')),
                ('role', models.CharField(choices=[('superadmin', 'Superadministrador da plataforma'), ('clinic_admin', 'Administrador da clinica'), ('receptionist', 'Recepcionista'), ('professional', 'Profissional'), ('patient', 'Paciente')], default='patient', max_length=32, verbose_name='perfil principal')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('is_staff', models.BooleanField(default=False, verbose_name='acessa o admin do Django')),
                ('mfa_enabled', models.BooleanField(default=False, verbose_name='MFA ativo')),
                ('mfa_secret', models.CharField(blank=True, editable=False, max_length=64)),
                ('mfa_confirmed_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('must_change_password', models.BooleanField(default=False, verbose_name='deve trocar a senha')),
                ('password_changed_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('failed_login_count', models.PositiveIntegerField(default=0, editable=False)),
                ('locked_until', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='bloqueado ate')),
                ('last_login_ip', models.GenericIPAddressField(blank=True, editable=False, null=True)),
                ('terms_accepted_at', models.DateTimeField(blank=True, null=True)),
                ('privacy_accepted_at', models.DateTimeField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'usuario',
                'verbose_name_plural': 'usuarios',
                'ordering': ['full_name'],
            },
            managers=[
                ('objects', apps.accounts.models.UserManager()),
            ],
        ),
    ]
