# Generated by Django 5.2.17 on 2026-08-24 23:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('clinics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apitoken',
            name='clinic',
            field=models.ForeignKey(blank=True, help_text='Restringe o token a uma clinica especifica.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='api_tokens', to='clinics.clinic'),
        ),
        migrations.AddField(
            model_name='apitoken',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_tokens', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='loginattempt',
            index=models.Index(fields=['email', '-created_at'], name='accounts_lo_email_f32d13_idx'),
        ),
        migrations.AddField(
            model_name='role',
            name='clinic',
            field=models.ForeignKey(blank=True, help_text='Vazio = modelo global disponivel para todas as clinicas.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='clinics.clinic', verbose_name='clinica'),
        ),
        migrations.AddField(
            model_name='usersession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role', 'is_active'], name='accounts_us_role_2b136f_idx'),
        ),
        migrations.AddConstraint(
            model_name='role',
            constraint=models.UniqueConstraint(fields=('clinic', 'name'), name='uniq_role_name_per_clinic'),
        ),
    ]
