# Generated by Django 5.2.17 on 2026-08-25 16:14

import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinics', '0002_initial'),
        ('documents', '0001_initial'),
        ('patients', '0001_initial'),
        ('professionals', '0001_initial'),
        ('scheduling', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CostCenter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='excluido')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='excluido em')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='ativo')),
                ('name', models.CharField(max_length=100, verbose_name='nome')),
                ('description', models.CharField(blank=True, max_length=250, verbose_name='descricao')),
                ('clinic', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='clinics.clinic', verbose_name='clinica')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='excluido por')),
            ],
            options={
                'verbose_name': 'centro de custo',
                'verbose_name_plural': 'centros de custo',
                'ordering': ['name'],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='FinancialCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='excluido')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='excluido em')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='ativo')),
                ('name', models.CharField(max_length=100, verbose_name='nome')),
                ('kind', models.CharField(choices=[('income', 'Receita'), ('expense', 'Despesa')], db_index=True, max_length=10, verbose_name='tipo')),
                ('description', models.CharField(blank=True, max_length=250, verbose_name='descricao')),
                ('clinic', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='clinics.clinic', verbose_name='clinica')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='excluido por')),
            ],
            options={
                'verbose_name': 'categoria financeira',
                'verbose_name_plural': 'categorias financeiras',
                'ordering': ['kind', 'name'],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='excluido')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='excluido em')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='ativo')),
                ('name', models.CharField(max_length=80, verbose_name='nome')),
                ('kind', models.CharField(choices=[('cash', 'Dinheiro'), ('pix', 'PIX'), ('credit_card', 'Cartao de credito'), ('debit_card', 'Cartao de debito'), ('transfer', 'Transferencia'), ('boleto', 'Boleto'), ('other', 'Outros')], default='other', max_length=20, verbose_name='tipo')),
                ('clinic', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='clinics.clinic', verbose_name='clinica')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='excluido por')),
            ],
            options={
                'verbose_name': 'forma de pagamento',
                'verbose_name_plural': 'formas de pagamento',
                'ordering': ['name'],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='PayableAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='excluido')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='excluido em')),
                ('supplier_name', models.CharField(max_length=150, verbose_name='fornecedor')),
                ('description', models.CharField(max_length=200, verbose_name='descricao')),
                ('issue_date', models.DateField(default=django.utils.timezone.localdate, verbose_name='data de lancamento')),
                ('due_date', models.DateField(verbose_name='data de vencimento')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='valor')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('partial', 'Parcialmente pago'), ('paid', 'Pago'), ('overdue', 'Vencido'), ('canceled', 'Cancelado')], db_index=True, default='pending', max_length=20, verbose_name='status')),
                ('notes', models.TextField(blank=True, verbose_name='observacoes')),
                ('attachment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='documents.document', verbose_name='comprovante')),
                ('category', models.ForeignKey(limit_choices_to={'kind': 'expense'}, on_delete=django.db.models.deletion.PROTECT, related_name='payables', to='finance.financialcategory', verbose_name='categoria')),
                ('clinic', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='clinics.clinic', verbose_name='clinica')),
                ('cost_center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payables', to='finance.costcenter', verbose_name='centro de custo')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='excluido por')),
                ('expected_payment_method', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='finance.paymentmethod', verbose_name='forma de pagamento prevista')),
            ],
            options={
                'verbose_name': 'conta a pagar',
                'verbose_name_plural': 'contas a pagar',
                'ordering': ['due_date'],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='ProfessionalCommissionRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='excluido')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='excluido em')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='ativo')),
                ('percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='percentual (%)')),
                ('fixed_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='valor fixo (R$)')),
                ('clinic', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='clinics.clinic', verbose_name='clinica')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='excluido por')),
                ('professional', models.ForeignKey(blank=True, help_text='Vazio = regra generica aplicada a qualquer profissional.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commission_rules', to='professionals.professional', verbose_name='profissional')),
                ('service', models.ForeignKey(blank=True, help_text='Vazio = regra generica aplicada a qualquer servico.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commission_rules', to='clinics.service', verbose_name='servico')),
            ],
            options={
                'verbose_name': 'regra de comissao',
                'verbose_name_plural': 'regras de comissao',
                'ordering': ['professional__full_name', 'service__name'],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='ReceivableAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='excluido')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='excluido em')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='descricao')),
                ('service_date', models.DateField(default=django.utils.timezone.localdate, verbose_name='data do atendimento')),
                ('due_date', models.DateField(verbose_name='data de vencimento')),
                ('gross_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='valor bruto')),
                ('discount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='desconto')),
                ('addition', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='acrescimo')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('partial', 'Parcialmente pago'), ('paid', 'Pago'), ('overdue', 'Vencido'), ('canceled', 'Cancelado')], db_index=True, default='pending', max_length=20, verbose_name='status')),
                ('notes', models.TextField(blank=True, verbose_name='observacoes')),
                ('professional_commission_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='valor do profissional')),
                ('clinic_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='valor da clinica')),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receivables', to='scheduling.appointment', verbose_name='agendamento')),
                ('category', models.ForeignKey(limit_choices_to={'kind': 'income'}, on_delete=django.db.models.deletion.PROTECT, related_name='receivables', to='finance.financialcategory', verbose_name='categoria')),
                ('clinic', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='clinics.clinic', verbose_name='clinica')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='excluido por')),
                ('expected_payment_method', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='finance.paymentmethod', verbose_name='forma de pagamento prevista')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receivables', to='patients.patient', verbose_name='paciente')),
                ('professional', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receivables', to='professionals.professional', verbose_name='profissional responsavel')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receivables', to='clinics.service', verbose_name='procedimento/servico')),
            ],
            options={
                'verbose_name': 'conta a receber',
                'verbose_name_plural': 'contas a receber',
                'ordering': ['due_date'],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='FinancialTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='excluido')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='excluido em')),
                ('kind', models.CharField(choices=[('income', 'Entrada'), ('expense', 'Saida')], db_index=True, max_length=10, verbose_name='tipo')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='valor')),
                ('paid_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='data/hora')),
                ('notes', models.CharField(blank=True, max_length=250, verbose_name='observacoes')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='finance.financialcategory', verbose_name='categoria')),
                ('clinic', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='clinics.clinic', verbose_name='clinica')),
                ('cost_center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='finance.costcenter', verbose_name='centro de custo')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='registrado por')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='excluido por')),
                ('payable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='finance.payableaccount', verbose_name='conta a pagar')),
                ('method', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='finance.paymentmethod', verbose_name='forma de pagamento')),
                ('receivable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='finance.receivableaccount', verbose_name='conta a receber')),
            ],
            options={
                'verbose_name': 'lancamento financeiro',
                'verbose_name_plural': 'lancamentos financeiros',
                'ordering': ['-paid_at'],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddConstraint(
            model_name='costcenter',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('clinic', 'name'), name='uniq_cost_center_per_clinic'),
        ),
        migrations.AddConstraint(
            model_name='financialcategory',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('clinic', 'kind', 'name'), name='uniq_financial_category_per_clinic'),
        ),
        migrations.AddConstraint(
            model_name='paymentmethod',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('clinic', 'name'), name='uniq_payment_method_per_clinic'),
        ),
        migrations.AddIndex(
            model_name='payableaccount',
            index=models.Index(fields=['clinic', 'status', 'due_date'], name='finance_pay_clinic__ca4f16_idx'),
        ),
        migrations.AddIndex(
            model_name='payableaccount',
            index=models.Index(fields=['clinic', 'cost_center'], name='finance_pay_clinic__596c7f_idx'),
        ),
        migrations.AddConstraint(
            model_name='professionalcommissionrule',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('clinic', 'professional', 'service'), name='uniq_commission_rule_per_clinic'),
        ),
        migrations.AddIndex(
            model_name='receivableaccount',
            index=models.Index(fields=['clinic', 'status', 'due_date'], name='finance_rec_clinic__af1e00_idx'),
        ),
        migrations.AddIndex(
            model_name='receivableaccount',
            index=models.Index(fields=['clinic', '-service_date'], name='finance_rec_clinic__304b25_idx'),
        ),
        migrations.AddIndex(
            model_name='financialtransaction',
            index=models.Index(fields=['clinic', '-paid_at'], name='finance_fin_clinic__496ed0_idx'),
        ),
        migrations.AddIndex(
            model_name='financialtransaction',
            index=models.Index(fields=['clinic', 'kind', '-paid_at'], name='finance_fin_clinic__feec12_idx'),
        ),
    ]
