# Generated by Django 5.2.17 on 2026-08-25 18:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0002_initial'),
        ('finance', '0001_initial'),
        ('patients', '0001_initial'),
        ('professionals', '0001_initial'),
        ('scheduling', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialtransaction',
            name='kind',
            field=models.CharField(choices=[('income', 'Entrada'), ('expense', 'Saida'), ('refund', 'Estorno')], db_index=True, max_length=10, verbose_name='tipo'),
        ),
        migrations.AlterField(
            model_name='payableaccount',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendente'), ('partial', 'Parcialmente pago'), ('paid', 'Pago'), ('overdue', 'Vencido'), ('canceled', 'Cancelado'), ('courtesy', 'Cortesia'), ('refunded', 'Estornado')], db_index=True, default='pending', max_length=20, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='receivableaccount',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendente'), ('partial', 'Parcialmente pago'), ('paid', 'Pago'), ('overdue', 'Vencido'), ('canceled', 'Cancelado'), ('courtesy', 'Cortesia'), ('refunded', 'Estornado')], db_index=True, default='pending', max_length=20, verbose_name='status'),
        ),
        migrations.AddConstraint(
            model_name='receivableaccount',
            constraint=models.UniqueConstraint(condition=models.Q(('appointment__isnull', False)), fields=('appointment',), name='uniq_receivable_per_appointment'),
        ),
    ]
