# Generated by Django 5.2.17 on 2026-08-24 23:05

import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinics', '0002_initial'),
        ('patients', '0001_initial'),
        ('professionals', '0001_initial'),
        ('scheduling', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='excluido')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='excluido em')),
                ('opened_at', models.DateTimeField(auto_now_add=True, verbose_name='aberto em')),
                ('summary', models.TextField(blank=True, verbose_name='resumo clinico')),
                ('alerts', models.TextField(blank=True, verbose_name='alertas importantes')),
                ('clinic', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='clinics.clinic', verbose_name='clinica')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='excluido por')),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='medical_record', to='patients.patient', verbose_name='paciente')),
            ],
            options={
                'verbose_name': 'prontuario',
                'verbose_name_plural': 'prontuarios',
                'ordering': ['-created_at'],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='MedicalRecordEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='excluido')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='excluido em')),
                ('title', models.CharField(blank=True, max_length=140, verbose_name='titulo')),
                ('data', models.JSONField(default=dict, verbose_name='conteudo')),
                ('attended_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='data do atendimento')),
                ('is_draft', models.BooleanField(db_index=True, default=True, verbose_name='rascunho')),
                ('signed_at', models.DateTimeField(blank=True, null=True, verbose_name='assinado em')),
                ('signature_hash', models.CharField(blank=True, editable=False, max_length=64, verbose_name='hash da assinatura')),
                ('version', models.PositiveIntegerField(default=1, editable=False, verbose_name='versao')),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='record_entries', to='scheduling.appointment', verbose_name='agendamento')),
                ('clinic', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='clinics.clinic', verbose_name='clinica')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='excluido por')),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='record_entries', to='professionals.professional', verbose_name='profissional')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='medical_records.medicalrecord', verbose_name='prontuario')),
                ('signed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'registro de atendimento',
                'verbose_name_plural': 'registros de atendimento',
                'ordering': ['-attended_at'],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='excluido')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='excluido em')),
                ('kind', models.CharField(choices=[('simple', 'Receita simples'), ('controlled', 'Receita de controle especial'), ('guidance', 'Orientacoes'), ('certificate', 'Atestado')], default='simple', max_length=20, verbose_name='tipo')),
                ('content', models.TextField(help_text='Um item por linha.', verbose_name='conteudo')),
                ('instructions', models.TextField(blank=True, verbose_name='orientacoes')),
                ('valid_until', models.DateField(blank=True, null=True, verbose_name='valido ate')),
                ('issued_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='emitida em')),
                ('released_to_patient', models.BooleanField(default=True, verbose_name='liberada no portal')),
                ('clinic', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='clinics.clinic', verbose_name='clinica')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='excluido por')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='patients.patient')),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prescriptions', to='professionals.professional')),
                ('record_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='medical_records.medicalrecordentry', verbose_name='atendimento')),
            ],
            options={
                'verbose_name': 'prescricao',
                'verbose_name_plural': 'prescricoes',
                'ordering': ['-issued_at'],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='RecordEntryRevision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='excluido')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='excluido em')),
                ('version', models.PositiveIntegerField(verbose_name='versao')),
                ('title', models.CharField(blank=True, max_length=140)),
                ('data', models.JSONField(default=dict)),
                ('reason', models.CharField(blank=True, max_length=250, verbose_name='motivo da alteracao')),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('clinic', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='clinics.clinic', verbose_name='clinica')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='excluido por')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='medical_records.medicalrecordentry')),
            ],
            options={
                'verbose_name': 'versao do registro',
                'verbose_name_plural': 'versoes do registro',
                'ordering': ['-version'],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='RecordTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='excluido')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='excluido em')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='ativo')),
                ('name', models.CharField(max_length=120, verbose_name='nome')),
                ('description', models.CharField(blank=True, max_length=250, verbose_name='descricao')),
                ('schema', models.JSONField(default=dict, verbose_name='estrutura')),
                ('is_default', models.BooleanField(default=False, verbose_name='modelo padrao')),
                ('clinic', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='clinics.clinic', verbose_name='clinica')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='excluido por')),
                ('specialty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='record_templates', to='clinics.specialty', verbose_name='especialidade')),
            ],
            options={
                'verbose_name': 'modelo de prontuario',
                'verbose_name_plural': 'modelos de prontuario',
                'ordering': ['-is_default', 'name'],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='medicalrecordentry',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entries', to='medical_records.recordtemplate', verbose_name='modelo'),
        ),
        migrations.AddConstraint(
            model_name='recordtemplate',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('clinic', 'name'), name='uniq_record_template_per_clinic'),
        ),
        migrations.AddIndex(
            model_name='medicalrecordentry',
            index=models.Index(fields=['clinic', '-attended_at'], name='medical_rec_clinic__195d57_idx'),
        ),
        migrations.AddIndex(
            model_name='medicalrecordentry',
            index=models.Index(fields=['record', '-attended_at'], name='medical_rec_record__2b7ef9_idx'),
        ),
        migrations.AddIndex(
            model_name='medicalrecordentry',
            index=models.Index(fields=['professional', '-attended_at'], name='medical_rec_profess_8f81bc_idx'),
        ),
    ]
