# Generated by Django 5.2.17 on 2026-08-25 18:52

import django.db.models.deletion
import django.db.models.manager
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0002_initial'),
        ('medical_records', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='kind',
            field=models.CharField(choices=[('simple', 'Receita simples'), ('controlled', 'Receita de controle especial'), ('guidance', 'Orientacoes'), ('certificate', 'Atestado'), ('declaration', 'Declaracao'), ('referral', 'Encaminhamento'), ('clinical_report', 'Relatorio clinico')], default='simple', max_length=20, verbose_name='tipo'),
        ),
        migrations.CreateModel(
            name='CIDCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='excluido')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='excluido em')),
                ('code', models.CharField(db_index=True, max_length=10, unique=True, verbose_name='codigo')),
                ('description', models.CharField(max_length=250, verbose_name='descricao')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='excluido por')),
            ],
            options={
                'verbose_name': 'codigo CID',
                'verbose_name_plural': 'codigos CID',
                'ordering': ['code'],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='VitalSigns',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='excluido')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='excluido em')),
                ('systolic_pressure', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='pressao sistolica (mmHg)')),
                ('diastolic_pressure', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='pressao diastolica (mmHg)')),
                ('heart_rate', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='freq. cardiaca (bpm)')),
                ('respiratory_rate', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='freq. respiratoria (irpm)')),
                ('temperature', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='temperatura (C)')),
                ('oxygen_saturation', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='saturacao O2 (%)')),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='peso (kg)')),
                ('height_cm', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='altura (cm)')),
                ('glucose', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='glicemia (mg/dL)')),
                ('notes', models.CharField(blank=True, max_length=250, verbose_name='observacoes')),
                ('clinic', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='clinics.clinic', verbose_name='clinica')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='excluido por')),
                ('entry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vital_signs', to='medical_records.medicalrecordentry', verbose_name='atendimento')),
            ],
            options={
                'verbose_name': 'sinais vitais',
                'verbose_name_plural': 'sinais vitais',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
