# Generated by Django 5.2.17 on 2026-08-24 23:05

import django.db.models.deletion
import django.db.models.manager
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinics', '0001_initial'),
        ('patients', '0001_initial'),
        ('professionals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='excluido')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='excluido em')),
                ('start_at', models.DateTimeField(db_index=True, verbose_name='inicio')),
                ('end_at', models.DateTimeField(verbose_name='fim')),
                ('status', models.CharField(choices=[('scheduled', 'Reservado'), ('confirmed', 'Confirmado'), ('checked_in', 'Aguardando atendimento'), ('in_progress', 'Em atendimento'), ('completed', 'Concluido'), ('canceled', 'Cancelado'), ('no_show', 'Faltou')], db_index=True, default='scheduled', max_length=20, verbose_name='status')),
                ('origin', models.CharField(choices=[('reception', 'Recepcao'), ('professional', 'Profissional'), ('portal', 'Portal do paciente'), ('api', 'Integracao')], default='reception', max_length=20, verbose_name='origem')),
                ('is_overbooking', models.BooleanField(default=False, verbose_name='encaixe')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='valor')),
                ('notes', models.TextField(blank=True, verbose_name='observacoes')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('checked_in_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('canceled_at', models.DateTimeField(blank=True, null=True)),
                ('cancel_reason', models.CharField(blank=True, max_length=200, verbose_name='motivo do cancelamento')),
                ('reminder_sent_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('canceled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('clinic', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='clinics.clinic', verbose_name='clinica')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='excluido por')),
                ('insurance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='clinics.insuranceplan', verbose_name='convenio')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='patients.patient', verbose_name='paciente')),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='professionals.professional', verbose_name='profissional')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='clinics.room', verbose_name='sala')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='clinics.service', verbose_name='servico')),
            ],
            options={
                'verbose_name': 'agendamento',
                'verbose_name_plural': 'agendamentos',
                'ordering': ['start_at'],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='ScheduleBlock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='excluido')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='excluido em')),
                ('kind', models.CharField(choices=[('holiday', 'Feriado'), ('vacation', 'Ferias'), ('absence', 'Ausencia'), ('meeting', 'Reuniao'), ('maintenance', 'Manutencao'), ('other', 'Outro')], default='absence', max_length=20, verbose_name='tipo')),
                ('start_at', models.DateTimeField(db_index=True, verbose_name='inicio')),
                ('end_at', models.DateTimeField(db_index=True, verbose_name='fim')),
                ('reason', models.CharField(blank=True, max_length=200, verbose_name='motivo')),
                ('clinic', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='clinics.clinic', verbose_name='clinica')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='excluido por')),
                ('professional', models.ForeignKey(blank=True, help_text='Vazio = bloqueio para toda a clinica.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedule_blocks', to='professionals.professional', verbose_name='profissional')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedule_blocks', to='clinics.room', verbose_name='sala')),
            ],
            options={
                'verbose_name': 'bloqueio de agenda',
                'verbose_name_plural': 'bloqueios de agenda',
                'ordering': ['-start_at'],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='ScheduleTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='excluido')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='excluido em')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='ativo')),
                ('weekday', models.PositiveSmallIntegerField(choices=[(0, 'Segunda-feira'), (1, 'Terca-feira'), (2, 'Quarta-feira'), (3, 'Quinta-feira'), (4, 'Sexta-feira'), (5, 'Sabado'), (6, 'Domingo')], verbose_name='dia da semana')),
                ('start_time', models.TimeField(verbose_name='inicio')),
                ('end_time', models.TimeField(verbose_name='fim')),
                ('slot_minutes', models.PositiveIntegerField(default=30, verbose_name='intervalo entre horarios (min)')),
                ('break_start', models.TimeField(blank=True, null=True, verbose_name='inicio do intervalo')),
                ('break_end', models.TimeField(blank=True, null=True, verbose_name='fim do intervalo')),
                ('valid_from', models.DateField(blank=True, null=True, verbose_name='valido a partir de')),
                ('valid_to', models.DateField(blank=True, null=True, verbose_name='valido ate')),
                ('clinic', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='clinics.clinic', verbose_name='clinica')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='excluido por')),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_templates', to='professionals.professional', verbose_name='profissional')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedule_templates', to='clinics.room', verbose_name='sala')),
            ],
            options={
                'verbose_name': 'disponibilidade',
                'verbose_name_plural': 'disponibilidades',
                'ordering': ['weekday', 'start_time'],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='WaitingListEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='excluido')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='excluido em')),
                ('preferred_period', models.CharField(choices=[('any', 'Qualquer'), ('morning', 'Manha'), ('afternoon', 'Tarde')], default='any', max_length=20, verbose_name='periodo preferido')),
                ('priority', models.CharField(choices=[('low', 'Baixa'), ('normal', 'Normal'), ('high', 'Alta'), ('urgent', 'Urgente')], default='normal', max_length=10, verbose_name='prioridade')),
                ('status', models.CharField(choices=[('waiting', 'Aguardando'), ('contacted', 'Contatado'), ('scheduled', 'Agendado'), ('canceled', 'Cancelado')], db_index=True, default='waiting', max_length=20, verbose_name='status')),
                ('notes', models.CharField(blank=True, max_length=250, verbose_name='observacoes')),
                ('contacted_at', models.DateTimeField(blank=True, null=True)),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='scheduling.appointment')),
                ('clinic', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='clinics.clinic', verbose_name='clinica')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='excluido por')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waiting_entries', to='patients.patient')),
                ('professional', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='waiting_entries', to='professionals.professional')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='clinics.service')),
            ],
            options={
                'verbose_name': 'lista de espera',
                'verbose_name_plural': 'lista de espera',
                'ordering': ['-priority', 'created_at'],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['clinic', 'start_at'], name='scheduling__clinic__1ece47_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['clinic', 'professional', 'start_at'], name='scheduling__clinic__33db9b_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['clinic', 'status'], name='scheduling__clinic__f41982_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['patient', '-start_at'], name='scheduling__patient_6b879b_idx'),
        ),
        migrations.AddIndex(
            model_name='scheduleblock',
            index=models.Index(fields=['clinic', 'start_at', 'end_at'], name='scheduling__clinic__075ef3_idx'),
        ),
        migrations.AddIndex(
            model_name='scheduletemplate',
            index=models.Index(fields=['clinic', 'professional', 'weekday'], name='scheduling__clinic__5a0bf3_idx'),
        ),
    ]
