# Generated by Django 5.2.17 on 2026-08-27 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='called_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Reservado'), ('confirmed', 'Confirmado'), ('checked_in', 'Aguardando atendimento'), ('called', 'Chamado'), ('in_progress', 'Em atendimento'), ('completed', 'Concluido'), ('canceled', 'Cancelado'), ('no_show', 'Faltou')], db_index=True, default='scheduled', max_length=20, verbose_name='status'),
        ),
    ]
