# Generated by Django 5.2.17 on 2026-09-01 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0002_appointment_called_at_alter_appointment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduletemplate',
            name='max_appointments',
            field=models.PositiveIntegerField(blank=True, help_text='Vazio = sem limite. A geracao de horarios para de gerar novos horarios (livres ou ocupados) assim que atingir este total.', null=True, verbose_name='maximo de atendimentos no dia'),
        ),
    ]
