# Generated by Django 5.2.17 on 2026-08-24 23:05

import apps.core.validators
import django.db.models.deletion
import django.db.models.manager
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='excluido')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='excluido em')),
                ('record_number', models.PositiveIntegerField(db_index=True, editable=False, verbose_name='prontuario')),
                ('full_name', models.CharField(db_index=True, max_length=180, verbose_name='nome completo')),
                ('social_name', models.CharField(blank=True, max_length=180, verbose_name='nome social')),
                ('cpf', models.CharField(blank=True, max_length=14, validators=[apps.core.validators.validate_cpf], verbose_name='CPF')),
                ('rg', models.CharField(blank=True, max_length=20, verbose_name='RG')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='data de nascimento')),
                ('gender', models.CharField(choices=[('F', 'Feminino'), ('M', 'Masculino'), ('O', 'Outro'), ('N', 'Nao informado')], default='N', max_length=1, verbose_name='sexo/genero')),
                ('marital_status', models.CharField(blank=True, max_length=40, verbose_name='estado civil')),
                ('occupation', models.CharField(blank=True, max_length=80, verbose_name='profissao')),
                ('nationality', models.CharField(blank=True, max_length=60, verbose_name='nacionalidade')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='e-mail')),
                ('phone', models.CharField(blank=True, max_length=20, validators=[apps.core.validators.validate_phone], verbose_name='telefone')),
                ('mobile', models.CharField(blank=True, max_length=20, validators=[apps.core.validators.validate_phone], verbose_name='celular')),
                ('whatsapp', models.CharField(blank=True, max_length=20, verbose_name='WhatsApp')),
                ('blood_type', models.CharField(blank=True, max_length=5, verbose_name='tipo sanguineo')),
                ('allergies', models.TextField(blank=True, verbose_name='alergias')),
                ('chronic_conditions', models.TextField(blank=True, verbose_name='condicoes cronicas')),
                ('continuous_medications', models.TextField(blank=True, verbose_name='medicamentos de uso continuo')),
                ('health_notes', models.TextField(blank=True, verbose_name='observacoes de saude')),
                ('insurance_number', models.CharField(blank=True, max_length=60, verbose_name='numero da carteirinha')),
                ('guardian_name', models.CharField(blank=True, max_length=180, verbose_name='responsavel legal')),
                ('guardian_document', models.CharField(blank=True, max_length=14, verbose_name='CPF do responsavel')),
                ('guardian_phone', models.CharField(blank=True, max_length=20, verbose_name='telefone do responsavel')),
                ('guardian_relationship', models.CharField(blank=True, max_length=60, verbose_name='parentesco')),
                ('status', models.CharField(choices=[('active', 'Ativo'), ('inactive', 'Inativo'), ('archived', 'Arquivado')], db_index=True, default='active', max_length=20, verbose_name='status')),
                ('referral_source', models.CharField(blank=True, max_length=80, verbose_name='como conheceu a clinica')),
                ('notes', models.TextField(blank=True, verbose_name='observacoes administrativas')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='patients/photos/', verbose_name='foto')),
                ('clinic', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='clinics.clinic', verbose_name='clinica')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='excluido por')),
                ('insurance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patients', to='clinics.insuranceplan', verbose_name='convenio')),
                ('portal_user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patient_profile', to=settings.AUTH_USER_MODEL, verbose_name='usuario do portal')),
            ],
            options={
                'verbose_name': 'paciente',
                'verbose_name_plural': 'pacientes',
                'ordering': ['full_name'],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='PatientAddress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='excluido')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='excluido em')),
                ('kind', models.CharField(choices=[('home', 'Residencial'), ('work', 'Comercial'), ('other', 'Outro')], default='home', max_length=20, verbose_name='tipo')),
                ('postal_code', models.CharField(blank=True, max_length=9, validators=[apps.core.validators.validate_cep], verbose_name='CEP')),
                ('street', models.CharField(blank=True, max_length=180, verbose_name='logradouro')),
                ('number', models.CharField(blank=True, max_length=20, verbose_name='numero')),
                ('complement', models.CharField(blank=True, max_length=80, verbose_name='complemento')),
                ('district', models.CharField(blank=True, max_length=100, verbose_name='bairro')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='cidade')),
                ('state', models.CharField(blank=True, max_length=2, verbose_name='UF')),
                ('is_primary', models.BooleanField(default=True, verbose_name='principal')),
                ('clinic', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='clinics.clinic', verbose_name='clinica')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='excluido por')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='patients.patient', verbose_name='paciente')),
            ],
            options={
                'verbose_name': 'endereco do paciente',
                'verbose_name_plural': 'enderecos do paciente',
                'ordering': ['-is_primary', 'kind'],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='PatientContact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='excluido')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='excluido em')),
                ('name', models.CharField(max_length=180, verbose_name='nome')),
                ('relationship', models.CharField(blank=True, max_length=60, verbose_name='parentesco/relacao')),
                ('phone', models.CharField(max_length=20, validators=[apps.core.validators.validate_phone], verbose_name='telefone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='e-mail')),
                ('is_emergency', models.BooleanField(default=True, verbose_name='contato de emergencia')),
                ('notes', models.CharField(blank=True, max_length=200, verbose_name='observacao')),
                ('clinic', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='clinics.clinic', verbose_name='clinica')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='excluido por')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='patients.patient', verbose_name='paciente')),
            ],
            options={
                'verbose_name': 'contato do paciente',
                'verbose_name_plural': 'contatos do paciente',
                'ordering': ['-is_emergency', 'name'],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['clinic', 'full_name'], name='patients_pa_clinic__f1cf8d_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['clinic', 'status'], name='patients_pa_clinic__d8d066_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['cpf'], name='patients_pa_cpf_e307a5_idx'),
        ),
        migrations.AddConstraint(
            model_name='patient',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False), models.Q(('cpf', ''), _negated=True)), fields=('clinic', 'cpf'), name='uniq_patient_cpf_per_clinic'),
        ),
        migrations.AddConstraint(
            model_name='patient',
            constraint=models.UniqueConstraint(fields=('clinic', 'record_number'), name='uniq_patient_record_per_clinic'),
        ),
    ]
